version: '3'
services:
  app:
    build: docker/php
    container_name: phplearn_app
    volumes:
      - ./:/var/www
    depends_on:
      - db
  nginx:
    image: nginx:1.17
    container_name: phplearn_nginx
    ports:
      - 8011:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/phplearn.local.conf:/etc/nginx/conf.d/phplearn.local.conf
    depends_on:
      - app
  db:
    image: mysql:8.0.23
    ports:
      - 3306:3306
    container_name: sphplearn_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: phplearn_db
      MYSQL_USER: phplearn_user
      MYSQL_PASSWORD: phplearn_pwd
      MYSQL_ALLOW_EMPTY_PASSWORD: 1